#!/usr/bin/env bash
set -euo pipefail

RUNDIR="$(readlink -f "$(dirname "$0")")"
cd "${RUNDIR}"

mkdir -p created

docker run --rm -it -u "$(id -u):$(id -g)" -v "$PWD:/home/debian/src" terrastruct/d2:v0.6.7 network_overview.d2 created/network_overview.svg
