name: pre-commit

on:
  pull_request:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install shfmt and shellcheck
        uses: awalsh128/cache-apt-pkgs-action@v1.2.2
        with:
          packages: shfmt shellcheck
          version: 1.0
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0
